# render.yaml

# 1. The managed PostgreSQL database
databases:
  - name: fintech-postgres-db
    # 'plan' can be free, starter, standard, etc.
    plan: free

# 2. The FastAPI web service
services:
  - type: web
    name: fintech-app
    env: python
    plan: free
    # Install your dependencies
    buildCommand: "uv pip sync"
    # Run any migrations or table-creation before starting
    preDeployCommand: >
      python -c "import asyncio; \
      from database import create_db_and_tables; \
      asyncio.run(create_db_and_tables())"
    # Launch Uvicorn on the assigned $PORT
    startCommand: "uv run --host 0.0.0.0 --port $PORT app:app"
    envVars:
      # automatically inject DATABASE_URL from the database above
      - key: DATABASE_URL
        fromDatabase:
          name: fintech-postgres-db
          property: connectionString
      # pull all your other secrets from this group
      - fromGroup: fintech-app-secrets
      - key: PYTHON_VERSION
        value: "3.11"
