# render.yaml

# 1. Managed Postgres stays under top-level `databases:`
databases:
  - name: fintech-postgres-db
    plan: free

# 2. Your FastAPI service
services:
  - type: web
    name: fintech-app
    env: python
    plan: free

    # 1) Install deps, 2) initialize the DB, all in one build step
    buildCommand: >
      uv sync  
    # python -c 'import asyncio; from database import create_db_and_tables; asyncio.run(create_db_and_tables())'

    # No more preDeployCommand
    startCommand: "uv run --host 0.0.0.0 --port $PORT app:app"

    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fintech-postgres-db
          property: connectionString
      - fromGroup: fintech-app-secrets
      - key: PYTHON_VERSION
        value: "3.11.0"
